services:
  - type: web
    name: cyzgo-telegram-bot
    env: php
    buildCommand: ""
    startCommand: php -S 0.0.0.0:$PORT
    envVars:
      - key:8345582227:AAFFozVMJsNEHPOcXddO0id1L4c_KKxxJsI
        sync: false  # 手动在Render后台设置
